Models/ErrorViewModel.cs
namespace basicMeetingApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/MeetingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace basicMeetingApp.Models
{
    public class MeetingInfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }

        public int NumberOfPeople { get; set; }
    }
}

Models/Repository.cs
namespace basicMeetingApp.Models
{
    public class Repository
    {
        private static List<UserInfo> _users = new();

        static Repository()
        {

            _users.Add(new UserInfo {Id=1, Name = "Ali", Email = "abc.gmail.com", Phone = "1111111", WillAttend = true });
            _users.Add(new UserInfo {Id=2, Name = "Ayşe", Email = "dfg.gmail.com", Phone = "2222222", WillAttend = false });
            _users.Add(new UserInfo {Id=3, Name = "Merve", Email = "axv.gmail.com", Phone = "3333333", WillAttend = true });
            _users.Add(new UserInfo {Id=4, Name = "Murat", Email = "yeq.gmail.com", Phone = "4444444", WillAttend = true });
        }
        public static List<UserInfo> Users
        {
            get
            {
                return _users;
            }
        }

        public static void AddResponse(UserInfo user)
        {   
            user.Id = Users.Count + 1;
            _users.Add(user);
        }

        public static UserInfo? GetById(int id)
        {
            return _users.FirstOrDefault(u => u.Id == id);
        }

    }
}

Models/UserInfo.cs
namespace basicMeetingApp.Models
{
    public class UserInfo
    {
        public int? Id { get; set; }
        public string? Name { get; set; }
        public string? Email { get; set; }
        public string? Phone { get; set; }
        public bool? WillAttend { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using basicMeetingApp.Models;

namespace basicMeetingApp.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
        int saat = DateTime.Now.Hour;
        ViewBag.Selamlama = saat > 12 ? "İyi Günler" : "Günaydın";
        int UserCount = Repository.Users.Where(i => i.WillAttend == true).Count();

        var meetingInfo = new MeetingInfo()
        {
            Id = 1,
            Location = "İstanbul",
            Date = new DateTime(2024, 12, 31),
            NumberOfPeople = UserCount
        };
        return View(meetingInfo);
    }
}

Controllers/MeetingController.cs
using Microsoft.AspNetCore.Mvc;
using basicMeetingApp.Models;

namespace basicMeetingApp.Controllers
{

    public class MeetingController : Controller
    {


        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model)
        {
            Repository.AddResponse(model);
            ViewBag.UserCount = Repository.Users.Where(i => i.WillAttend == true).Count();
            return View("Thanks",model);
        }
        public IActionResult List()
        {
            return View(Repository.Users);
        }

        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }


    }
}

Views/Home/Index.cshtml
@model MeetingInfo
@{
ViewBag.Title = "Toplantı Başvuru";
Layout = "_Layout2";
}

<div class="text-center">
  <h1 class="h4">@ViewBag.Selamlama</h1>
  <h2 class="h6">Toplantı katılım durumunuzu bildirin</h2>
  <div class="card my-2">
    <ul class="list-group list list-group-flush">
      <li class="list-group-item">@Model.Location</li>
      <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy") tarihinde gerçekleşecek</li>
      <li class="list-group-item">@Model.NumberOfPeople Katılımcı</li>
    </ul>
  </div>


  <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvuru Yap
  </a>
</div>

Views/Meeting/Apply.cshtml
@model UserInfo

@{
ViewBag.Title = "Başvuru Formu";
}
<h1 class="h4 text-center">Toplantı Katılım Formu</h1>
<form method="post" action="/Meeting/Apply">

    <div class="mb-3">
        <label asp-for="Name" class="form-label">Ad Soyad</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Telefon</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">E-posta</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Katılım Durumu</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="true">Evet, Geliyorum</option>
            <option value="false">Hayır, Gelmiyorum</option>
        </select>
    </div>

    <button class="btn btn-outline-primary" type="submit">Kaydet</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo


<main class="text-center">
    <h1 class="h4">Başvuru Detayı</h1>
    <p>İsim: @Model.Name</p>
    <p>Email: @Model.Email</p>
    <p>Telefon: @Model.Phone</p>

</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
    @{
    ViewBag.Title = "Toplantı Katılım Listesi";
    }

    <main class="text-center">
        <h1 class="h4">TOplantıya Katılım Listesi</h1>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>Ad</td>
                    <td>Katılım Durumu</td>
                    <td>Detay</td>
                </tr>
            </thead>
            <tbody>

                @{int i = 0;}
                @foreach (var user in Model)
                {

                var attendance = user.WillAttend == true ? "Evet" : "Hayır";
                var className = user.WillAttend == true ? "table-success" : "table-danger";

                if(user.WillAttend == true)
                {
                i++;
                }

                <tr class="@className">
                    <td>@user.Name</td>
                    <td>@attendance</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="/meeting/details/user.Id">Detay</a>
                    </td>
                </tr>
                }


            </tbody>
        </table>
        <div class="card">
            <div class="card-body">
                <span>Katılımcı Sayısı : @i</span>
            </div>
        </div>
    </main>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
ViewBag.Title = "Başvuru Durumu";
}
<main class="text-center">
    <h1 class="h4">Başvuru Durumu</h1>

    @if(Model.WillAttend==true)
    {
    <p>Teşekkürler, @Model.Name toplantıya sizinle birlikte @ViewBag.UserCount kişi katılıyor.</p>
    <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>
    }else{
    <p>@Model.Name, katılamadığından üzgünüz.</p>
    <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru Formu</a>
    }




</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>@ViewBag.Title - MeetingApp</title>
  </head>
  <body>
    <div class="bg-primary tex-white p-2 text-center">MeetingApp</div>
    <div class="container mt-3">
      <div class="row">
        <div class="col-lg-6 mx-auto">
          <div class="card">
            <div class="card-body">
                @RenderBody()
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>@ViewBag.Title - MeetingApp</title>
  </head>
  <body>
    <div class="bg-success tex-white p-2 text-center">MeetingApp</div>
    <div class="container mt-3">
      <div class="row">
        <div class="col-lg-6 mx-auto text-center">
          <div class="card">
            <div class="card-body">
                @RenderBody()
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>